# Generated by Django 2.2.9 on 2020-01-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_headline_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
