# Generated by Django 2.2.9 on 2020-01-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_headline_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
